name: JekyllDeploy
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.3.5'
      - name: build static site
        run: rake build
      - name: create mdbook documentation
        run: rake book
